AppBundle\Entity\KommoWebhook:
  type: entity
  repositoryClass: AppBundle\Repository\KommoRepository
  table: kommo_webhook
  id:
    id:
      type: integer
      nullable: false
      id: true
      generator:
        strategy: IDENTITY
  fields:
    webhookType:
      type: string
      length: 50
      nullable: false
    kommoId:
      type: string
      length: 100
      nullable: false
    jsonRecibido:
      type: json
      nullable: false
    estado:
      type: string
      length: 30
      nullable: true
    errorMensaje:
      type: text
      nullable: true
    fecha:
      type: datetime
      nullable: false