AppBundle\Entity\SimuladorUsoEmail:
  type: entity
  table: simulador_uso_email
  repositoryClass: AppBundle\Repository\SimuladorUsoEmailRepository
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    email:
      type: string
      length: 255
    usos:
      type: integer
      options:
        default: 1
    primerUso:
      type: datetime
      column: primer_uso
    ultimoUso:
      type: datetime
      column: ultimo_uso
    tipo:
      type: string
      length: 100
      options:
        default: 'general'
  indexes:
    idx_email:
      columns: [email]
  uniqueConstraints:
    uniq_email_tipo:
      columns: [email, tipo]